# Generated by Django 2.0 on 2022-05-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0029_auto_20190606_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ci_allowed',
            field=models.BooleanField(default=True, help_text="If disabled, users won't be able to login with electronic CI", verbose_name='Electronic CI Allowed'),
        ),
    ]
