# Generated by Django 2.0 on 2022-05-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0030_client_ci_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gub_uy_allowed',
            field=models.BooleanField(default=True, help_text="If disabled, users won't be able to login with Gub Uy accounts.", verbose_name='Gub Uy Allowed'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ci_allowed',
            field=models.BooleanField(default=True, help_text="If disabled, users won't be able to login with electronic CI.", verbose_name='Electronic CI Allowed'),
        ),
    ]
